spring:
  datasource:
    url: jdbc:h2:mem:test;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialize: false
  h2:
    console:
      enabled: true
      path: /h2